---
apiVersion: v1
kind: Namespace
metadata:
  name: clusters-sub
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: clusters
  namespace: openshift-gitops
spec:
  generators:
    - git:
        repoURL: https://github.com/natifridman/vse-carslab-hub.git
        revision: cars-lab-4-12
        directories:
          - path: clusters/ztp-siteconfig/*
  template:
    metadata:
      name: '{{path.basename}}-siteconfig'
    spec:
      project: ztp-app-project
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 15
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 5m
        syncOptions:
          - CreateNamespace=true
      source:
        path: '{{path}}'
        repoURL: https://github.com/natifridman/vse-carslab-hub.git
        targetRevision: cars-lab-4-12
      destination:
        server: https://kubernetes.default.svc
        namespace: clusters-sub
