---
apiVersion: metal3.io/v1alpha1
kind: Provisioning
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: provisioning-configuration
spec:
  provisioningNetwork: Disabled
  disableVirtualMediaTLS: false
  watchAllNamespaces: true
